//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int ID { get; set; }
        public byte[] Image { get; set; }
        public string Extension { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Enabled { get; set; }
    }
}
