//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeFileZH
    {
        public int ID { get; set; }
        public string ItemType { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public string Remark { get; set; }
        public System.DateTime Created { get; set; }
        public int Creator { get; set; }
        public System.DateTime Modified { get; set; }
        public int Modify { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
