//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string NUSF { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Telmobile { get; set; }
        public string Fax { get; set; }
    }
}
