//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelEN()
        {
            this.RoomEN = new HashSet<RoomEN>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Game { get; set; }
        public int City { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
        public string Features { get; set; }
        public string LinkUrl { get; set; }
        public string Facilities { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public int UserId { get; set; }
        public string Tel { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomEN> RoomEN { get; set; }
    }
}
