//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageStore
    {
        public int ID { get; set; }
        public byte[] Image { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> ReferIdZH { get; set; }
        public Nullable<int> ReferIdUS { get; set; }
        public string ReferNameZH { get; set; }
        public string ReferNameUS { get; set; }
        public string Extension { get; set; }
        public System.DateTime Created { get; set; }
        public bool Deleted { get; set; }
    }
}
