//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGHotel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WGHotelsEntities : DbContext
    {
        public WGHotelsEntities()
            : base("name=WGHotelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<CityEN> CityEN { get; set; }
        public virtual DbSet<CityZH> CityZH { get; set; }
        public virtual DbSet<CodeFileEN> CodeFileEN { get; set; }
        public virtual DbSet<CodeFileZH> CodeFileZH { get; set; }
        public virtual DbSet<FacilityEN> FacilityEN { get; set; }
        public virtual DbSet<FacilityZH> FacilityZH { get; set; }
        public virtual DbSet<GameSiteEN> GameSiteEN { get; set; }
        public virtual DbSet<GameSiteZH> GameSiteZH { get; set; }
        public virtual DbSet<HotelEN> HotelEN { get; set; }
        public virtual DbSet<HotelZH> HotelZH { get; set; }
        public virtual DbSet<ImageStore> ImageStore { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<ReportRooms> ReportRooms { get; set; }
        public virtual DbSet<SysSetting> SysSetting { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<VenueEN> VenueEN { get; set; }
        public virtual DbSet<VenueZH> VenueZH { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<RoomPrice> RoomPrice { get; set; }
        public virtual DbSet<RoomEN> RoomEN { get; set; }
        public virtual DbSet<RoomZH> RoomZH { get; set; }
        public virtual DbSet<Log> Log { get; set; }
    }
}
