//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report()
        {
            this.ReportRooms = new HashSet<ReportRooms>();
        }
    
        public int ID { get; set; }
        public string Country { get; set; }
        public int CountryID { get; set; }
        public int HotelID { get; set; }
        public int RoomID { get; set; }
        public int Creator { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> NumOfPeople { get; set; }
        public string Remark { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime Modified { get; set; }
        public int Modify { get; set; }
        public string Room { get; set; }
        public Nullable<decimal> FoodCost { get; set; }
        public string Other { get; set; }
        public Nullable<decimal> OtherCost { get; set; }
        public string Food { get; set; }
        public string UserType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportRooms> ReportRooms { get; set; }
    }
}
