//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomPrice
    {
        public int ID { get; set; }
        public int ROOMID { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Date { get; set; }
        public bool SaleOff { get; set; }
        public int Quantity { get; set; }
    }
}
