//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomZH
    {
        public int ID { get; set; }
        public int HOTELID { get; set; }
        public string Name { get; set; }
        public string RoomType { get; set; }
        public string BedType { get; set; }
        public string Facilities { get; set; }
        public Nullable<bool> HasBreakfast { get; set; }
        public Nullable<decimal> Sell { get; set; }
        public string Notice { get; set; }
        public Nullable<int> Quantiy { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Feature { get; set; }
    
        public virtual HotelZH HotelZH { get; set; }
    }
}
