//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueZH
    {
        public int ID { get; set; }
        public string Sport { get; set; }
        public string Venue { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
